#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to a YouTube page

apt-get update
apt-get -y install nginx

if ! grep -q "location /redirect_me" /etc/nginx/sites-enabled/default; then
    sed -i '/server_name _;/a\        location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-enabled/default
fi

service nginx restart
